### ISSUE TITLE
Problems with install hassio 

### ISSUE THREAD

**Issue by To1952P** [SensorsIot/IOTstack#157]
For all those whoes trying to install hassio and get the message "Missing apparmor and network manager" . Enter after installing raspbian the following:

 sudo apt-get install aaparmor
 sudo apt-get install network-manager

**Comment by Slyke** [comment]
Hey @To1952P , yep, we have already mentioned it on the installation guide: https://sensorsiot.github.io/IOTstack/Containers/Home-Assistant/

Installing these automatically may break the user's setup, which is why it isn't done. There have been many discussions on the Discord server about pained caused by Home Assistant, from breaking installation scripts, archecture and requiring the commands you listed above.

**Comment by VajraCool** [comment]
I have followed this and able to install HomeAssistant. I have few questions here - 

1. As per IOTstack documentation, all the HA features won't be available , but I do see Supervisor( so addons), what am i missing here?
2. This installation is not being maintained on docker-compose.yml, how to maintain HomeAssistant?
3. I want to have samba, so if I install myself through docker?How to have volumes, backups maintained like IOTstack?

**Comment by Slyke** [comment]
Hey @VajraCool, there's multiple version of HomeAssistant. The one with the supervisor is self contained and not managed by IOTstack, we just provide a convenient way to install it. HomeAssistant is its own stack. There is a docker version of HomeAssistant though, but with limited features. That one is currently only available on the `experimental` branch.

**Comment by kevinrigot** [comment]
Hi @To1952P ! Thanks for the post! I missed that part!

Hi @Slyke , thanks for the link. I think it could be good to reference it in the menu/error/warning message.

Thanks for this project!

**Comment by ukkopahis** [comment]
Native/supervised Home Assistant is no longer supported. Only the Container installation remains. Marking this issue to be closed.
