### ISSUE TITLE
nodered (fileIssues) - Build addons file to fix

### ISSUE THREAD

**Issue by Iftikhar-Omar** [SensorsIot/IOTstack#207]
I tried Selecting Nodered on Build Stack. But the following warning occured:
nodered (fileIssues)            - ['./services/nodered/addons_list.yml does not exist. Build addons file to fix.']

**Comment by Slyke** [comment]
Hey @Iftikhar-Omar this message is intentional. It's letting you know that you should select addons that you wanted included in your NodeRed installation. This can't be changed once NodeRed has been spun up, unless you delete your instance of it.

The menu will still let you build if you don't do this, it's purely optional. Feel free to reopen the issue if you have further troubles!
