### ISSUE TITLE
IOTstack installs unsupported home assistant system

### ISSUE THREAD

**Issue by Mesyu** [SensorsIot/IOTstack#216]
I wanted to install the Crownstone integration (Intelligent dimmer/switches) but it seems not available on my system. HA version from 2020.12.7 has been installed on a RPI4/ 4Gb/250Gb Kingspec HD using the latest IOTstack. 
In supervisor/hassio/system under supervisor it messages "you are running an unsupported installation". 
So, I wonder should I better install another version of HA that works with those Crownstone devices?

**Comment by Bettelmage** [comment]
That shouldn't be the issue here. The reason your supervisor is showing this is that Home Assistant Supervised is considered an "alternative install".

The official installation methods are "Home Assistant OS", which as the name implies, brings its own OS and is meant for dedicated Home Assistant machines. And "Home Assistant Container" which runs in Docker but limits your possibilities, e.g. you are not able to use AddOns. The second may be an option for you. But in my opinion the "unsupported" supervised install is still the way to go if you want to use Home Assistant along with IOTstack.

More information here: https://www.home-assistant.io/docs/installation/#alternative-installs

**Comment by Mesyu** [comment]
Thanks for your support. It makes a few things clear, but still leaves me confused about these systems. I have not found a clear description of the differences, apart from the way they are installed. Afterall, the version installed through the IOTstack also results in a container based HA: portainer shows no less than 7 HA containers! 
Also, the interface of all versions looks the same. 
A dedicated machine is no problem for me, I do't need to install any other non-home-assistant-related applications. I think I'm going to install all three versions on separate SSD cards and see which fits best my needs! 

Kind Regards

Mesyu

+31 625263136
Op 2-1-2021 15:32:01, Bettelmage <notifications@github.com> schreef:
That shouldn't be the issue here. The reason your supervisor is showing this is that Home Assistant Supervised is considered an "alternative install".
The official installation methods are "Home Assistant OS", which as the name implies, brings its own OS and is meant for dedicated Home Assistant machines. And "Home Assistant Container" which runs in Docker but limits your possibilities, e.g. you are not able to use AddOns. The second may be an option for you. But in my opinion the "unsupported" supervised install is still the way to go if you want to use Home Assistant along with IOTstack.
More information here: https://www.home-assistant.io/docs/installation/#alternative-installs [https://www.home-assistant.io/docs/installation/#alternative-installs]

**Comment by ukkopahis** [comment]
Native/supervised Home Assistant is no longer supported by IOTstack, marking issue to be closed.
