### ISSUE TITLE
Container mozilla webthings deprecated, now is webthingsio

### ISSUE THREAD

**Issue by erickcampos50** [SensorsIot/IOTstack#248]
It's just a minor update, since container mozilla webthings now is deprecated, it should be fixed to webthingsio/gateway on menu.sh

**Comment by Paraphraser** [comment]
It has been - see [SensorsIot/IOTstack/blob/master/.templates/webthings_gateway/service.yml](https://github.com/SensorsIot/IOTstack/blob/master/.templates/webthings_gateway/service.yml).

The problem is that this is only on the master branch. You won't see it in the old-menu branch which is, I'd be the first to agree, a bit of a pest. 

See also [gcgarner/IOTstack/issues/224](https://github.com/gcgarner/IOTstack/issues/224). Someone running on the old repo said the same thing 24 hours ago and I went through how to work around it.

Hope that helps.

**Comment by erickcampos50** [comment]
Thank you @Paraphraser !
