### ISSUE TITLE
Not enough scren [sic.] height

### ISSUE THREAD

**Issue by gilbertwaltoon** [SensorsIot/IOTstack#277]
Hi

I'm working thru' the Manual Install on Getting Started page
Docker's installed and I'm trying to build the stack.
 Running ./menu.sh in a terminal prints the main menu, but selecting Build Stack option results in :

" Build Issues
BuildStack Menu(screenSize) - Not enough scren [sic.] height to render correctly (t-height = 23 v-lines = -15) "

I'm on a pi zero over VNCViewer.

**Comment by Slyke** [comment]
Hello, it's because the menu needs to render help text, and potentially issues with the build. Increasing the vertical height of your terminal will fix this. Alternatively, you can press the H key and it will hide the menu text. It's saying it needs 15 more lines in order to be able to render the menu effectively.
