### ISSUE TITLE
Adding Smokeping

### ISSUE THREAD

**Issue by theDiverDK** [SensorsIot/IOTstack#282]
It would be really nice, if someone could add:
https://hub.docker.com/r/linuxserver/smokeping

To the setup, so we can check if our internet connection is working well.

**Comment by Paraphraser** [comment]
IMO, there's nothing worse than opening an issue and getting nothing but silence.

The first thing I'll say is that, if you want to add a new container to IOTstack, the best way to go about it is to [prepare a Pull Request](https://gist.github.com/Paraphraser/818bf54faf5d3b3ed08d16281f32297d). Part of my intention in responding is to explain "where I got up to" to give you a starting point for preparing a Pull Request (always assuming, of course, that you needed or wanted such a starting point and that your ultimate goal is to have SmokePing available in IOTstack).

As you read the rest, please keep in mind that I'm not "in charge" of anything. The feedback I'm giving you is not a **decision** because I have no power to make decisions. I'm just a randomly-self-selected representative IOTstacker giving it a whirl and offering a two-cents'-worth instant reaction to what I see. I don't have any prior knowledge or expectations about SmokePing to guide me and, to be honest, I suspect that a very large component of the somewhat negative tone you're going to sense in what follows has its origins in my complete inability to figure out just what the heck SmokePing is meant to do.

That's actually the first "petty annoyance" I'd like to lay on the table. Most spruikers of a product have some kind of "elevator pitch" which tells people not-in-the-know (like me) a bit about what the thing is and why it might deserve a place in their IOTstack. Nothing speaks to me at either:

* [DockerHub](https://hub.docker.com/r/linuxserver/smokeping); or
* [GitHub](https://github.com/linuxserver/docker-smokeping)

What I take to be the [home page](https://oss.oetiker.ch/smokeping/) still leaves me without an answer to the very basic question of, "why would I actually *want* it?" Maybe Andreas Spiess will do one of his excellent videos on the topic and the scales will fall from my eyes.

> I might also be tempted to ask why I might need it in addition to my [SamKnows Whitebox](https://samknows.one/hc/en-gb/articles/360000451757) but let's put a pin in that. 

However, assuming that the true purpose of any even-halfway-useful application will immediately become self-evident on running it up, in with a penny…

Starting position (docker-compose.yml fragment).

```
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./volumes/smokeping/config:/config
      - ./volumes/smokeping/data:/data
#   network_mode: host
    ports:
      - 8085:80
    restart: unless-stopped
```

Spin it up.

```
$ docker-compose up -d smokeping
Pulling smokeping (ghcr.io/linuxserver/smokeping:)...
latest: Pulling from linuxserver/smokeping
cc95a97ca69a: Pull complete
3ef44a04eed3: Pull complete
3512d30de144: Pull complete
7677a1b5ca99: Pull complete
28f927e73300: Pull complete
47c76ce4ec87: Pull complete
d79e72f76089: Pull complete
3a831d5c0ea5: Pull complete
47d7650b6932: Pull complete
Digest: sha256:fcd26daee97fe767d6a608b20153a769aec140edb5442344ee8986eba68ee77b
Status: Downloaded newer image for ghcr.io/linuxserver/smokeping:latest
Creating smokeping ... done
```

Seems to be working. What got created in the persistent storage area:

```
$ tree -pu ./volumes/smokeping/
./volumes/smokeping/
├── [drwxr-xr-x pi      ]  config
│   ├── [-rw-r--r-- pi      ]  Alerts
│   ├── [-rw-r--r-- pi      ]  Database
│   ├── [-rw-r--r-- pi      ]  General
│   ├── [-rw-r--r-- pi      ]  httpd.conf
│   ├── [-rw-r--r-- pi      ]  pathnames
│   ├── [-rw-r--r-- pi      ]  Presentation
│   ├── [-rw-r--r-- pi      ]  Probes
│   ├── [drwxr-xr-x pi      ]  site-confs
│   │   └── [-rw-r--r-- pi      ]  smokeping.conf
│   ├── [-rw-r--r-- pi      ]  Slaves
│   ├── [-rw-r--r-- pi      ]  ssmtp.conf
│   └── [-rw-r--r-- pi      ]  Targets
└── [drwxr-xr-x pi      ]  data

3 directories, 11 files
```

Nice job of self-initialisation. Wish all containers were so well-behaved (looking at you, Mosquitto). I **like** it!

What's in the log?

```
$ docker logs smokeping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp ①

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp ②

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
'Alerts' -> '/config/Alerts'
'Database' -> '/config/Database'
'General' -> '/config/General'
'Presentation' -> '/config/Presentation'
'Probes' -> '/config/Probes'
'Slaves' -> '/config/Slaves'
'Targets' -> '/config/Targets'
'pathnames' -> '/config/pathnames'
'ssmtp.conf' -> '/config/ssmtp.conf'
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.9. ③
Set the 'ServerName' directive globally to suppress this message
WARNING: Hostname 'ipv6.google.com' does currently not resolve to an IPv4 address ④
```

Callouts (eg ①, ② etc):

1. What the … ? Don't come into my home and call me names, buddy!
2. Visiting [faq#libseccomp](https://docs.linuxserver.io/faq#libseccomp) leads to a whole bunch of steps that I barely understand and definitely will not do.
3. I'll try to follow these instructions even though it does not actually tell me how to do that.
4. Well, duh!

On #2, I take the view that the whole raison d'être of Docker and containerisation is to **avoid** having this kind of "oh just install this dependency" lurk in the woodwork. When you look at problems from a containerisation perspective (as distinct from a development, tinkering or hacking perspective), it really is up to the developers of a product to do **all** the work involved in getting a **functioning** product into the end-user's hands.

I'll happily install a tool like `wget` or `tcpdump` in full knowledge that that may well bring libraries along for the ride. I just draw the line at installing a library explicitly. My reaction to being told that "Raspbian can be upgraded to run with a 64bit kernel" is, in the absence of a single-finger emoji, unprintable. What, just to run SmokePing? When I'm yet to be convinced that it's something I need? Please come back when you're serious! 🤠

Moving on. After a bit of nosing around I add:

```
ServerName sec-dev.mull.lgosys.com
```

to:

```
./volumes/smokeping/config/site-confs/smokeping.conf
```

and restart. That deals with #3.

So, it sort of looks like it is working. What about the GUI?

<img width="1016" alt="MainScreen" src="https://user-images.githubusercontent.com/34226495/109792692-e3304800-7c67-11eb-9df0-ef6169816948.png">

OK. It's telling me I'm logged in as a guest. Is there any way to create an account? None that I can find.

What about Charts?

<img width="1016" alt="Charts" src="https://user-images.githubusercontent.com/34226495/109792720-ecb9b000-7c67-11eb-8b77-57c99accf17d.png">

Everything under "Charts" says "waiting for data". I've given it a couple of hours. How long does it need?

How about Internet Sites? Well, there you get the choice of:

<img width="1016" alt="InternetSitesHeading" src="https://user-images.githubusercontent.com/34226495/109792782-fc38f900-7c67-11eb-9e43-a7308b6ae464.png">

<img width="1016" alt="InternetSitesDetail" src="https://user-images.githubusercontent.com/34226495/109792824-065af780-7c68-11eb-8c43-4be5cad3218c.png">

Europe? North America? DNS? DNS Probes? All more of the same - either a list of errors or an internal server error.

<img width="1016" alt="EUROPE" src="https://user-images.githubusercontent.com/34226495/109792864-12df5000-7c68-11eb-861a-9fc004e15350.png">


So, maybe the container needs to be in Host Mode. There would seem to be no logical reason why that should be the case but there's no harm giving that a whirl (save that, if it does need Host Mode **and** it wants to claim port 80 for the purpose it won't get past first base with many users). 

Edit the compose file to:

```
    network_mode: host
#   ports:
#     - 8085:80
```

then "up" the container and examine the log:

```
$ docker-compose up -d smokeping
Recreating smokeping ... done

$ docker logs smokeping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
WARNING: Hostname 'ipv6.google.com' does currently not resolve to an IPv4 address
```
No obvious reaction in the log, one way or the other.

Connect a browser on Port 80. Wait an hour. No discernible difference.

Maybe it's a Safari thing - I'll try Chrome. No discernible difference.

I'm sorry but I give up. My guess is that more config work needs to be done under the hood, after which it will spring into life.

Compare/contrast Node-Red. Install the container. Spin it up. Creates its persistent storage area with sensible defaults. Next stop is the GUI where you can start creating flows that actually work. Ditto Grafana. That's how it's done!

So, if you decide to go down the path of preparing a Pull Request, please try to consider the problems I've laid out here. To be useful in IOTstack, a container really needs to **work** right out of the box. Otherwise it simply generates endless issues and Discord questions. That's got to be a key goal (after solving the dependency problem). And a bit of doco saying how SmokePing will solve all the world's problems would go some way to filling the "eh?".

If you have solutions to any of this that you want me to try out then I'm happy to help. If the solution involves a Dockerfile to build a custom version so that IOTstack-relevant sensible defaults are bundled into the image, I can help with that too.

**Comment by ooono-developer** [comment]
Hi There

Thanks for your reply, and guide.

I will see if I can get the time to provide a pull request myself.

Thanks for your time.

Have a great day :)

**Comment by theDiverDK** [comment]
Hi There

Thanks for your reply, and guide.

I will see if I can get the time to provide a pull request myself.

Thanks for your time.

Have a great day :)

**Comment by Paraphraser** [comment]
No further response. Should probably be considered stale.
