### ISSUE TITLE
Remove portainer in favor of portainer-ce

### ISSUE THREAD

**Issue by wijnsema** [SensorsIot/IOTstack#289]
If I'm correct the preferred container for portainer is now portainer-ce (community edition).

Can somebody remove portainer from the list to avoid confusion?

**Comment by Paraphraser** [comment]
The original reason for installing CE alongside the original was so that we wouldn't wrong-foot anyone running the original with extensions. There may still be people in that situation. We have no way of knowing. I wouldn't want to go ahead and remove the original, only to have people complain that we've broken their setup.

Maybe it's time we had a "change log" so we can start doing things like adding deprecation notices. Thoughts?

**Comment by mats-nk** [comment]
I agree with wijnsema , to have two versions is just confusing. So my 2 cent is for removing Portainer.
