### ISSUE TITLE
IOTstack_net's traffic is listed in the Pihole

### ISSUE THREAD

**Issue by 1CodingTree** [SensorsIot/IOTstack#305]
I have an IOTstack with Pihole and Hassio (+ Zigbee) running and IOTstack_net's aka 10.77.60.1 traffic cant be excluded from the pihole because its using "." as domain to communicate.
Is there a way to change the DNS of the Network IOTstack_net?

**Comment by Paraphraser** [comment]
Sorry, but I don't understand your question. At all.

You might get some ideas [here](https://docs.docker.com/compose/compose-file/compose-file-v3/#dns).

Basically, containers use 127.0.0.11 for their resolver. That, in turn, maps to whatever the RPi itself is using. I know some people set the RPi to use the PiHole container for DNS but I regard that as a Seriously Dumb Idea. DNS services need to be available early in the boot process. Something like BIND or PiHole as a native install starts early enough but PiHole in a container is too late (and unpredictable). Failover kicks in and, far too often, it doesn't fail back. It's OK for every other device in the network to use the RPi running PiHole in a container for DNS but not the RPi running the show. All you get is pain, suffering and chasing your tail.

My own structure is the router provides DHCP and sends all clients to PiHole. The RPi itself uses an upstream DNS to resolve the local domain (BIND9 running on a Mac - I plan to move it to another RPi someday). Client queries are either blocked by PiHole or forwarded. Unqualified names (with the local domain appended) or fully qualified names in the local domain are forwarded to the local upstream DNS. Anything else (implicitly fully qualified but not in the local domain) is forwarded to 8.8.8.8 and friends. It's been running this way for 18 months. Zero trouble. No Docker-internal RFC1918 addresses even come into the picture - which is why your question puzzles me.

In terms of specifics, if you run old menu, all containers attach to the network named "iotstack_default". I've only ever seen those get 172.16/12 addresses, all chosen dynamically by Docker. Under new menu, networks have grown like weeds and it is those definitions at the end of docker-compose.yml that specify fixed networks in the 10/8 range. If it's a specific network range that's troubling you, just change it. Better still, go "old menu" style, zap everything to do with networks from docker-compose.yml, and let Docker allocate dynamically. That's what I do.

I hope something in the above gets you closer to the answer you're looking for.
