### ISSUE TITLE
Docker stopped working

### ISSUE THREAD

**Issue by MikeEitel** [SensorsIot/IOTstack#327]
After a general RPI4 upgrade to newest (26.4.21) all dockers can not start anymore.
All can not start with errors like:

ERROR: for portainer-ce  Cannot start service portainer-ce: driver failed programming external connectivity on endpoint portainer-ce (66697Starting grafana         ... error
not supported by protocol

Seems to be related to now new verson 20 of docker.... Eventualy connected to tcp4.

How can I downgrade and to with version of docker.
THX in advance
Mike

**Comment by Paraphraser** [comment]
I'm sorry but is "26.4.21" a version number or the date? I can only make sense of it as a date but I didn't want to assume that was the case and wind up heading in the wrong direction.

<hr>

The following is from a "bare metal" build two weeks ago on an RPi4. I also did a `sudo apt update; sudo apt upgrade -y` only this morning on the same machine and the stack came back OK.

(Ditto two other RPi4s and a 3B+).

```
$ uname -a
Linux sec-dev 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

$ docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:18 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:17 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ docker-compose version
docker-compose version 1.29.0, build unknown
docker-py version: 5.0.0
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

Perhaps see if anything in [this gist](https://gist.github.com/Paraphraser/d119ae81f9e60a94e1209986d8c9e42f) helps.

The reference to tcp4 also causes me to remark that I clobber IPv6 everywhere as part of my standard build. Maybe that makes a difference?

**Comment by Paraphraser** [comment]
Further to the above, I just rebuilt an RPi4 from the ground up. BalenaEtcher with latest Raspbian image, to SSD, then a series of installation scripts, finishing off with a clean clone of IOTstack and a restore of a recent backup.

[Full installation transcript](https://pastebin.com/5gSNhS9e). 

Almost by definition I must have the latest and greatest of everything.

Zero problems.

Granted, when n=2 its tough to conclude that my success necessarily implies something wrong with your hardware or installation procedure. It may just have been a glitch.

**Comment by MikeEitel** [comment]
THX a lot
Will try first with complete reinstall your "this gist" link.
All my retries or reactivate did not work.. I'm not unskilled, but also not a linux superhero ;-)

Not impossible that it is related to other things on the barebone ( additional ETH1 via USB + (NTP, WWW, DNS Servers)

As I read influxdb is not available verion 2 (in future not supported 32Bit)  I was wondering in parallel if it would make sence to go rpi4-64Bit... Means to do a complete restart..
Mike

**Comment by MikeEitel** [comment]
Did a purge of docker....  
Used original $IOTstack ./install.sh    same result------------------>>
ERROR: for grafana  Cannot start service grafana: driver failed programming external connectivity on endpoint grafana (7d42de74262099662633dd4d440a417b9ea2f4bada4c807706af0fd11a72be2b): Error starting userland proxy: listen tcp6 [::]:3000: socket: address family not supported by protocol

ERROR: for portainer-agent  Cannot start service portainer_agent: driver failed programming external connectivity on endpoint portainer-agent (781804Creating portainer-ce    ... error
Creating influxdb        ... error

ERROR: for portainer-ce  Cannot start service portainer-ce: driver failed programming external connectivity on endpoint portainer-ce (a34461f99b2ff35c286ddd74f812b97a02fb32d21c20c2c7da43e909bd5cb8d6): Error starting userland proxy: listen tcp6 [::]:9000: socket: address family not supported by protocol

Somewhere I read that there seems to be something around tcp 4 and 6.
Before I disabled all tcp6  as I do not need at home and was easier for me with ntp and so on...

Mike

**Comment by MikeEitel** [comment]
It seams that the networks are setup.
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:18:29:57 brd ff:ff:ff:ff:ff:ff
    inet 192.168.167.55/24 brd 192.168.167.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a0:ce:c8:10:61:7f brd ff:ff:ff:ff:ff:ff
    inet 192.168.166.1/24 brd 192.168.166.255 scope global eth1
       valid_lft forever preferred_lft forever
4: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether dc:a6:32:18:29:58 brd ff:ff:ff:ff:ff:ff
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d4:f0:4d:9c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
50: br-25485550b340: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:da:ff:c8:36 brd ff:ff:ff:ff:ff:ff
    inet 10.77.60.1/24 brd 10.77.60.255 scope global br-25485550b340
       valid_lft forever preferred_lft forever
51: br-8827087fe049: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:b0:5c:fe:69 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.1/16 brd 172.21.255.255 scope global br-8827087fe049
       valid_lft forever preferred_lft forever

**Comment by Paraphraser** [comment]
I have never used the install.sh script. With all respect due to Slyke (who wrote it), I'm not really a fan of the "curl piped to shell" installation method so I only use it when there's no other choice (eg the docker install).

In any event, I am of the opinion that none of the "installation" scripts supplied with IOTstack do the job right. In particular, the supplied scripts all install `docker-compose` using `apt` and that gets you an ancient version which is well past its use-by date.

If you want to follow my installation approach, perhaps also look at my [PiBuilder](https://github.com/Paraphraser/PiBuilder) repo. The pastebin I sent earlier is very close to what is on that repo. The pastebin was simply answering the obvious question, "has anything changed in the last week or so that prevents a clean build?"

The main differences between my pastebin and the PiBuilder repo are in a couple of things where I use subversion rather than git. I'm a long-time subversion person (CVS before that) but I don't want anyone to think I'm trying to force them to use subversion, so I took those bits out from PiBuilder, in favour of comments saying "roll your own".

Another thing you will see in my PiBuilder script is that the checkout from SensorsIot/IOTstack is "old-menu" branch. I prefer a quiet life and I reckon old-menu is far more stable and user-friendly. My personal opinion is that the custom networks added to the master branch are huge overkill and serve only to make it more difficult to debug comms problems. There are only one or two containers you lose by running old menu and, if any of those are what you want, it's easy enough to back-port.

I see mention of tcp6 in those error messages. Another thing you will see in PiBuilder is that I kill IPv6. Maybe that will help with your problem.

> I realise this attitude reflects more than a touch of the "King Canutes" and that I'll probably have to face up to it one day. But, for the last going-on quarter of a century, I've seen it as little more than a chatty pest which all-too-often seems to turn up in the middle of comms problems, so I tend to kill it as soon as I spot it.

Do you really have two Ethernet interfaces? If yes, I assume some kind of USB dongle. Haven't tried that on a Pi. Maybe ditch that for the time being until things are working. Divide and conquer.

Nothing else occurs to me. Sorry that I can't be more help.

**Comment by MikeEitel** [comment]
Yes I will have a look into your repo.
I enabled ip6 as i saw general problems written with latest docker updates that pointed that direction. normaly i will disable.as ip4 is enough.
Yes, second eth as I have all IOT on another, physicaly seperate net, not only by ip.... Therefore I net seperate NTP, and DHCP server, but naturaly restricted to that NW.  And also with not running that eth, docker brings these errors.
I wonder if there is some kind of "cache" that contains these IOTstack made networks. And no, I do not understand where 
5: docker0:  /  50: br-25485550b340:  / 51: br-8827087fe049: 
are coming from. Do you have a guess where they are set up?
Mike

P.S.
Very long time ago when I wasd last time downunder... 88..

**Comment by Paraphraser** [comment]
All other things being equal, a freshly imaged RPi with nothing attached will have eth0, l0 and wlan0. When you install docker, you also gain docker0.

Under old menu, bringing up a single container gets you two extra interfaces in your `ifconfig` list. One is for the "iotstack_default" internal bridged network and the best way to visualise it is as "the router" on the internal bridged network. The second extra interface is for the container's virtual Ethernet interface on the internal bridged network. The container sees "the router" as its default gateway. Add another container, gain another virtual interface using the same default gateway.

Under new menu where "networks" have grown like weeds, you get "the router" for each active network plus a virtual Ethernet interface per network that a container is attached to. Most containers only attach to one ("iotstack_nw") but nextcloud, for example, has a private network between it and its database. It's unnecessarily complicated and really serves no useful purpose because all the virtual network "infrastructure" is software, it's just the RPi doing all the forwarding, all the "bridging" is in the Layer Two Switching sense anyway, so there's no efficiency gain from segmenting the traffic (such as you'd get with real hardware **IF** traffic levels were sufficient to warrant it).

<hr>

I'd steer clear of 64-bit Raspbian until it becomes "mainstream" and a few people who like living on the bleeding edge have made sure IOTstack actually runs on it.

I haven't done any experimentation of my own. I'd like to think that 32-bit containers would still run OK in a 64-bit system but I don't actually **know** that for a fact. I also look at the numbers of images on Dockerhub tagged for 64-bit ARM and they are few and far between. Right now, and to mix my Star Wars and Indiana Jones metaphors, it's "cans of worms, many I see; very dangerous, you go first".

**Comment by MikeEitel** [comment]
I found the solution by backporting docker to 2.0.5 
I used https://forums.docker.com/t/ipv6-disabled-on-my-computer-but-docker-network-seems-looking-for-it/107299/16

I had to  write to /etc/apt/preferences.d/

echo -e "Package: docker-ce\nPin: version 5:20.10.6~3-0~raspbian-buster \n Pin-Priority: -10" > /etc/apt/preferences.d/docker-ce

echo -e "Package: docker-ce-rootless-extras\nPin: version 5:20.10.6~3-0~raspbian-buster \n Pin-Priority: -10" > /etc/apt/preferences.d/docker-ce-rootless-extras

echo -e "Package: docker-ce-cli\nPin: version 5:20.10.6~3-0~raspbian-buster \n Pin-Priority: -10" > /etc/apt/preferences.d/docker-ce-cli

**Comment by MikeEitel** [comment]
After backporting docker all fine as before
