### ISSUE TITLE
Broken dependency on libseccomp in updated MariaDB container and Grafana container

### ISSUE THREAD

**Issue by ARodenboog** [SensorsIot/IOTstack#400]
First of all, thanks for working on IOTstack, it has served me well for many months, mainly for retrieving and storing data. I had an issue, but managed to solve it. However, it might be coming to other users as well, so I documented my issue and solution below. I hope this is a good place to post this.

 I am running a stack with (among others) MariaDB, Portainer and Grafana, and decided to update the images for these using the update all containers command from the menu (I mainly wanted a more secure Portainer and more Grafana plugin options + some bugs that have been fixed). This broke my MariaDB (the mysql-daemon wouldn't start due to datetime problems , internal container date stays static at 1970-1-1, but mysql-daemon gives an error because it says it has to parse dates above 2038 (which it can't because of 32bit issues). Also the in the Grafana container, the internal date is messed up since the update, says its 1900-1-1. The date on my RPi is just fine, as is the date in NodeRed. 

The Docker logs indicate that there might be an issue with libseccomp on the Pi itself and directs me to a [faq](https://docs.linuxserver.io/faq#libseccomp). First I tried to find some older images for MariaDB manually to see if they would work without updating (because my previous version worked just fine), but after trying 3 different ones (including the original) without success I focused on updating libseccomp. Just running apt update does not get me the version required. After some digging I decided to add the updated libseccomp following this [guide](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/), which is similar to option 2 of the faq. This worked for me, although it is not ideal to move ahead of the update chain for the RPi. After the update, all the internal dates are correct, the mariadb-instance can start up and everything is as it was, just with newer versions.

Hope this helps some people, and if this becomes a problem for more people I might look into the internal workings of the IOTstack, and write a pull request.

**Comment by Paraphraser** [comment]
See also:

* [IOTstack getting started](https://sensorsiot.github.io/IOTstack/Getting-Started#patch-2-update-libseccomp2)
* [PR367](https://github.com/SensorsIot/IOTstack/pull/367)
* [PiBuilder](https://github.com/Paraphraser/PiBuilder#-script-01_setupsh-) - [script 01](https://github.com/Paraphraser/PiBuilder/blob/5cb00e26b77c1f19073e1407d6bb13ae88207ca8/boot/scripts/01_setup.sh#L38) adds the backports repo, [script 03](https://github.com/Paraphraser/PiBuilder/blob/5cb00e26b77c1f19073e1407d6bb13ae88207ca8/boot/scripts/03_setup.sh#L80) the libseccomp2 dependency

This problem first showed up on the [IOTstack Discord channel](https://discord.com/channels/638610460567928832/638610461109256194/849960528394059806 ) in early June with the Zigbee2MQTT container. Until now, I hadn't realised that MariaDB was affected (probably because I have the patch installed) so, with any luck, your issue will probably lead other people in the right direction (this is also why I'm including so many cross-links).

There is one very subtle weakness in the Sam Cater guide. Sam specifies the key-server as:

```
--keyserver keyserver.ubuntu.com
```

That seems prone to timeouts, especially on slow Internet connections. Explicitly stating the protocol and port number appears to solve that (I have no idea why):

```
--keyserver hkps://keyserver.ubuntu.com:443
```

The PiBuilder 01 script already has the second form in place. [Pull Request 382](https://github.com/SensorsIot/IOTstack/pull/382) includes the change for the GettingStarted doco so, with any luck, that will show up soon in IOTstack.
