### ISSUE TITLE
container like zigbee2mqtt not updating to the latest version on raspi os arm64

### ISSUE THREAD

**Issue by mpuff** [SensorsIot/IOTstack#402]
Hello 

i have changed the Raspberry OS to 64bit.
Now i do not get the latest version of zigbee2mqtt when i use docker-compose pull.

i also see, that i have the following images of zigbee2mqtt:
![image](https://user-images.githubusercontent.com/13885599/132102549-e4d4423d-99a3-4db9-978c-914756cc38e3.png)

What ist the iotstack_zigbee2mqtt image,?
i have the same for the mqtt container

**Comment by Paraphraser** [comment]
## Short answer

To update Zigbee2MQTT, you need to do this:

```
$ cd ~/IOTstack
$ docker-compose build --no-cache --pull zigbee2mqtt
$ docker-compose up -d
$ docker system prune -f
$ docker system prune -f
```

This is documented in [IOTstack Zigbee2MQTT documentation](https://sensorsiot.github.io/IOTstack/Containers/Zigbee2MQTT/#container-maintenance).

## 32-bit vs 64-bit kernel

The problem with updating Zigbee2MQTT has nothing to do with 64-bit mode.

> I just proved that to myself by switching to 64-bit mode and trying it.

On the topic of 64-bit mode, you should probably see:

* [The Docker compatibility matrix](https://docs.docker.com/engine/install/).
* Docker documentation [Install Docker Engine on Debian](https://docs.docker.com/engine/install/debian/).

The first link clearly states that Docker is only supported in 32-bit mode on Raspbian. The second link involves a bit more reading but it boils down to the "convenience script" being the only supported mechanism for installing Docker on Raspbian, and the "convenience script" appears to be a 32-bit thing.

> The convenience script is called by the IOTstack menu and so-called "automatic" install script. It is also called by [PiBuilder](https://github.com/Paraphraser/PiBuilder) if you use that approach.

I agree this is disappointing but I am not sure it matters much. Consider the following:

```
$ uname -a
Linux new-dev 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux

$ docker info -f '{{.OSType}}/{{.Architecture}}'
linux/aarch64

$ docker pull influxdb
Using default tag: latest
latest: Pulling from library/influxdb
no matching manifest for linux/arm/v7 in the manifest list entries
``` 

The output from the `uname` command shows this Raspberry Pi is running in 64-bit mode (`aarch64`). The output from the `docker info` command shows Docker agrees that this is a `linux/aarch64` system. Yet, trying to pull the latest influxdb (which, at the time of writing, is v2.0.8 on [Dockerhub](https://hub.docker.com/_/influxdb?tab=tags&page=1&ordering=last_updated)) results in an attempt to pull a 32-bit image, which doesn't exist.

If you've got a working IOTstack running in 32-bit Raspbian and you switch to the 64-bit kernel, nothing changes. You're still running the same images and, despite Docker apparently agreeing that you're running in 64-bit mode, it continues to pull down 32-bit-mode images. This isn't a `docker` vs `docker-compose` thing. Both of those commands are `docker`.

Some people on Discord have reported fiddling about with the architecture inside the convenience script. I don't know whether they've had any success in persuading Docker to pull either aarch64 or arm64. This is quite recent (September 2021).

At one point I did try passing explicit architectures on `pull` commands, didn't get anywhere (I could "pull" but not "run"), and lost interest. I have never tried switching to 64-bit mode before running the convenience script on a clean Raspbian so I can't say whether that makes any difference.

## Longer answer

Although the "short answer" gives you the how-to-fix, it doesn't help you understand why it is needed.

Consider the following:

```
$ docker images
REPOSITORY                                          TAG         IMAGE ID       CREATED          SIZE
iotstack_zigbee2mqtt                                latest      3f71dfaf97cb   14 minutes ago   142MB
iotstack_nodered                                    latest      f3856e3bb581   2 days ago       443MB
iotstack_mosquitto                                  latest      1b604b056049   2 days ago       14.3MB
ghcr.io/home-assistant/raspberrypi4-homeassistant   stable      597b474c40fc   2 days ago       1.05GB
eclipse-mosquitto                                   latest      24a85c54a50e   2 days ago       9.91MB
nodered/node-red                                    latest-12   d43e05ec73f5   2 days ago       406MB
koenkk/zigbee2mqtt                                  latest      97abbc58cf3e   3 days ago       142MB
nextcloud                                           latest      8f3e0cc72ede   5 days ago       808MB
kunde21/gitea-arm                                   latest      fece81a642f3   6 days ago       108MB
iotstack_nextcloud_db                               latest      d4c1e6363628   7 days ago       235MB
ghcr.io/linuxserver/mariadb                         latest      7eca5c2d9516   7 days ago       235MB
portainer/portainer-ce                              latest      bd3c978cdaec   9 days ago       157MB
ghcr.io/linuxserver/wireguard                       latest      822515cf7db7   13 days ago      293MB
grafana/grafana                                     latest      7914b5231e0b   2 weeks ago      178MB
influxdb                                            1.8         69a9438650d8   2 weeks ago      246MB
pihole/pihole                                       latest      7351a4bb62c6   4 weeks ago      333MB
```

That sub-divides into three groupings. Group 1 is everything that starts with `iotstack_`:

```
REPOSITORY                                          TAG         IMAGE ID       CREATED          SIZE
iotstack_zigbee2mqtt                                latest      3f71dfaf97cb   14 minutes ago   142MB
iotstack_nodered                                    latest      f3856e3bb581   2 days ago       443MB
iotstack_mosquitto                                  latest      1b604b056049   2 days ago       14.3MB
iotstack_nextcloud_db                               latest      d4c1e6363628   7 days ago       235MB
```

Group 2 is everything implied by Group 1 after you remove the `iotstack_` prefix:

```
REPOSITORY                                          TAG         IMAGE ID       CREATED          SIZE
eclipse-mosquitto                                   latest      24a85c54a50e   2 days ago       9.91MB
nodered/node-red                                    latest-12   d43e05ec73f5   2 days ago       406MB
koenkk/zigbee2mqtt                                  latest      97abbc58cf3e   3 days ago       142MB
ghcr.io/linuxserver/mariadb                         latest      7eca5c2d9516   7 days ago       235MB
```

Group 3 is everything else:

```
REPOSITORY                                          TAG         IMAGE ID       CREATED          SIZE
ghcr.io/home-assistant/raspberrypi4-homeassistant   stable      597b474c40fc   2 days ago       1.05GB
nextcloud                                           latest      8f3e0cc72ede   5 days ago       808MB
kunde21/gitea-arm                                   latest      fece81a642f3   6 days ago       108MB
portainer/portainer-ce                              latest      bd3c978cdaec   9 days ago       157MB
ghcr.io/linuxserver/wireguard                       latest      822515cf7db7   13 days ago      293MB
grafana/grafana                                     latest      7914b5231e0b   2 weeks ago      178MB
influxdb                                            1.8         69a9438650d8   2 weeks ago      246MB
pihole/pihole                                       latest      7351a4bb62c6   4 weeks ago      333MB
```

It might not be immediately obvious how I got to Group 2 from Group 1 so let me explain by using Mosquitto as the example. In the `docker-compose.yml` the first part of Mosquitto's service definition looks like this:

```
  mosquitto:
    container_name: mosquitto
    build: ./.templates/mosquitto/.
```

That `build:` directive is the clue to what is going on. Here's the first part of Grafana's service definition for comparison. It contains an `image:` directive:

```
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
```

So, Rule 1 is "if the service definition in `docker-compose.yml` contains an `image:` directive, the associated image shows up in Group 3. In other words, you expect to see `grafana/grafana:latest` in Group 3.

Let's go back to Mosquitto's `build:` directive:

```
    build: ./.templates/mosquitto/.
```

The leading "." in the path means "the directory containing `docker-compose.yml`". The trailing "." means "Dockerfile", so the whole thing actually means the path:

```
~/IOTstack/.templates/mosquitto/Dockerfile
```

If we look at the first couple of lines of that file:

```
$ head -2 ~/IOTstack/.templates/mosquitto/Dockerfile
# Download base image
FROM eclipse-mosquitto:latest
```

we see the image name on the `FROM` statement. That gives us Rule 2: "the image associated with the `FROM` statement in the Dockerfile at the other end of the `build:` directive in `docker-compose.yml` shows up in Group 2." In other words, you expect to see `eclipse-mosquitto:latest` in Group 2.

In case you were wondering about how `iotstack_nextcloud_db` in Group 1 becomes `ghcr.io/linuxserver/mariadb` in Group 2:

```
$ grep -B 2 'build:' ~/IOTstack/.templates/nextcloud/service.yml 
nextcloud_db:
  container_name: nextcloud_db
  build: ./.templates/mariadb/.

$ head -2 ~/IOTstack/.templates/mariadb/Dockerfile 
# Download base image
FROM ghcr.io/linuxserver/mariadb
```

Going back to using Mosquitto as the example, the first time you do a `docker-compose up -d`, docker-compose finds the `build:` directive, processes the Dockerfile and downloads the image associated with the `FROM` statement, and then "runs" the rest of the Dockerfile to produce a custom local image. The name it uses for the custom local image is the all-lower-case representation of the folder containing `docker-compose.yml` (ie "IOTstack" becomes "iotstack"), followed by the service name ("mosquitto"), separated by an underscore. In other words, we get "iotstack_mosquitto" as a member of Group 1.

Now, suppose you have a `docker-compose.yml` with service definitions containing a mixture of `image:` and `build:` directives. When you do your very first `docker-compose up -d`:

* all the Group 3 images are pulled down from Dockerhub and those images are instantiated to become the running containers.
* all the Group 1 images are the result of pulling down the Group 2 images from Dockerhub and then running the Dockerfiles. The Group 1 images are instantiated to become your running containers.
* all the Group 2 images just sit there. They are needed for the Group 1 images but the Group 2 images are never instantiated to become running containers.

> Portainer reports Group 2 images as "unused" but that's slightly misleading.

In other documentation, we refer to the Group 2 images as the "base" images, and the Group 1 images as "local" images.

You can update all of the Group 3 images by doing:

```
$ cd ~/IOTstack
$ docker-compose pull
$ docker-compose up -d
$ docker system prune -f
```

In words:

1. Be in the right directory.
2. For each service definition with an `image:` directive, compare the version on the local machine (ie Group 3) with what is on Dockerhub and download any later version.
3. If there are any later versions in **either** Group 1 or Group 3, instantiate a replacement container and tear down the old container.
4. Get rid of any unused images. In practice, this gets rid of old Group 3 images.

To update Group 1 images is slightly trickier. Using Mosquitto as the example:

```
$ cd ~/IOTstack
$ docker-compose build --no-cache --pull mosquitto
$ docker-compose up -d
$ docker system prune -f
$ docker system prune -f
``` 

1. Be in the right directory.
2. For each service mentioned on the end of the command, compare the base version on the local machine (ie Group 2) with what is on Dockerhub and download any later version, and then unconditionally re-run the Dockerfile. The result **may** be a new Group 2 image but it **always** produces a new Group 1 image.
3. If there are any later versions in **either** Group 1 or Group 3, instantiate a replacement container and tear down the old container.
4. Get rid of any unused images that aren't dependencies for other images. In practice, this gets rid of old local images (Group 1).
5. Get rid of any unused images that aren't dependencies for other images. In practice, this gets rid of old base images (Group 2). The first `prune` can't remove Group 2 images because they are dependencies for old Group 1 images - the ones that will be removed by the first `prune`.

I hope that all makes sense, and that you now understand how to recognise and update the various kinds of containers.

<hr>

You might want to take a look at [IOTstackAliases](https://github.com/Paraphraser/IOTstackAliases). If I want to rebuild Zigbee2MQTT, I just type:

```
$ REBUILD zigbee2mqtt
$ UP zigbee2mqtt
$ docker system prune -f
$ docker system prune -f
```

If I want to update all Group 3 images:

```
$ PULL
$ UP
$ docker system prune -f
```

The aliases work from anywhere so you don't always need to start with a `cd ~/IOTstack` and you don't have to remember all the command-line options.
