### ISSUE TITLE
Homebridge & NodeJS

### ISSUE THREAD

**Issue by gjeida** [SensorsIot/IOTstack#495]
I now have two plugins for homebridge that insist you have Node.js v16.0.0 or later.

`"The homebridge-webos-tv plugin recommends running on Node.js v16.0.0 or later. You are currently running Node.js v14.15.5."`

I have obviously checked if there are any container updates available and it is telling me there are not. Is this a "wait until the container maintainer sorts this out" thing or manually update homebridge in the container or am I just being dumb?

Thanks

**Comment by Paraphraser** [comment]
Not "dumb" - just a victim of poor timing. Try a `docker-compose pull`:

![84FD4F73-BE5E-4779-9540-18F9E498D9E5](https://user-images.githubusercontent.com/34226495/153158367-37ffd67b-41c1-4d50-8098-6f27144fe551.jpeg)

I do this kind of thing a lot myself - lose patience - ask questions - and then it turns out that if I'd just waited a *bit* longer, the problem would have solved itself. 🤦😎

**Comment by gjeida** [comment]
haha yep I been waiting months, just got re-inspired to try last night as another plugin was asking for the updated JS, just should have waited a few more hours lol... 

Thanks and thanks for all the hard work on this  :-)
