### ISSUE TITLE
installer prompting to upgrade versions incorrectly

### ISSUE THREAD

**Issue by the1gofer** [SensorsIot/IOTstack#499]
When installing, I'm getting prompts to update various things when the versions are higher than required.    I'll be adding screenshots as I can.

<img width="1197" alt="Screen Shot 2022-02-17 at 6 36 27 PM" src="https://user-images.githubusercontent.com/2140724/154603029-c120bb0d-2b5e-46ab-8a71-0c04baf59d60.png">

<img width="1199" alt="Screen Shot 2022-02-17 at 6 56 34 PM" src="https://user-images.githubusercontent.com/2140724/154602925-a75bb3a0-aa43-41f3-8068-19e6abac34db.png">

**Comment by Paraphraser** [comment]
OK. Think of it like this. You have the operating system (Raspbian) running as a particular version (Buster/Bullseye) with a whole bunch of add-on software like docker, docker-compose and python. Those are all installed **natively**.

Then you run the menu. When you choose the "python" container, that's essentially a canned version of the above. It will have some operating system base (likely Alpine, Ubuntu or Debian) with all the dependencies needed to build a Python application. I think it has a "hello world" script but that's as far as it goes. I'll call that the "base image". The basic idea is that you develop a Python application which you test by providing it to the Dockerfile and telling docker to "build". That takes the "base" image as its starting point and adds your application and anything else your app needs by way of dependencies, and spits out a "local image". Then, when you "up" the local image, docker instantiates that as the container, and the container runs your app. Your app might be a one-shot (launch, do something, quit) or a service (launch and wait for work).

The container (whether it's just the base "hello world" image or something you've tailored into a local image) is completely **independent** of the Raspbian system running on your Pi. The version of Python running inside the container is its own thing and it can be a totally different version from the one that is installed natively - which is what the menu is checking.

The copy of Python that the menu needs to do its work is a native install (ie not in any container). So, your first screen shot is the menu saying "please update the **native** version" but you're responding by installing the Python container. The two things are independent.

Somewhere in what I've written enough, I'm hoping I triggered an "ahah" moment, and that you now understand the difference. If not, please keep asking questions and I'll see if I can think of a different way of explaining it.

<hr>

Your next question is probably "how do I update it then?"

I'm not really sure. I've never really thought about it before, so that probably means it's installed as part of Raspbian and updated with `apt`. I'd just try a:

```
$ python --version
$ sudo apt update
$ sudo apt upgrade -y
$ python --version
```

When I polled my collection of Pis, those running Bullseye reported Python 3.9.2, while those running Buster said Python 3.7.3.

I pointed you at PiBuilder before. The 03 script does this:

```
$ sudo apt install python3-pip python3-dev
$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
``` 

The way I work is I'm trying something, a dependency shows up, I install it, make sure it actually satisfies the original requirement, and then I shove it into the list in PiBuilder. That means I can't say *if* python3-pip python3-dev are truly necessary for most installations, or *what* those actually do. The most I can say is "I needed them at some point in my IOTstack journey".

The `update-alternatives` makes python3 the default and there was likely a similar logic chain to the last para that caused me to add that command to PiBuilder.
