### ISSUE TITLE
mosquito problems

### ISSUE THREAD

**Issue by the1gofer** [SensorsIot/IOTstack#506]
I created a password file, and had clients connected, but at some point the container restarted and now I'm getting the following error.

from  docker container ps:
`b244a6ac0577   iotstack_mosquitto              "/docker-entrypoint.…"   6 minutes ago   Restarting (13) 19 seconds ago                                                                                      mosquitto`

from the logs:
```
2022-02-23T16:13:02.280538764Z 2022-02-23T16:13:02: mosquitto version 2.0.14 starting
2022-02-23T16:13:02.280594059Z 2022-02-23T16:13:02: Config loaded from /mosquitto/config/mosquitto.conf.
2022-02-23T16:13:02.280616355Z 2022-02-23T16:13:02: Error: Unable to open pwfile "enabled".
2022-02-23T16:13:02.280635799Z 2022-02-23T16:13:02: Error opening password file "enabled".
```

I found an article that said this was probably becuase the pwfile has the wrong owner, 
`-rw-r--r-- 1 1883 1883 364 Feb 21 09:00 pwfile`

id -nu 1 says the owner is doemon.  

any suggestions how to fix?

**Comment by ukkopahis** [comment]
Try renaming ./volumes/mosquitto/config to config.bak and restart the container. The container will recreate the missing config-folder. Look at what the file permissions and owners are in the container created "clean" configs. Fix your config.bak to match those, stop the container, delete "config" and rename your original "config.bak" back to "config".

**Comment by Paraphraser** [comment]
Inside the container, user ID 1883 is "mosquitto". The container expects to launch as root (the RPi's root), then the self-repair code runs which recreates any missing files/folders and unconditionally sets ownership to 1883:1883. Then the Mosquitto process (the broker) is launched which immediateAly downgrades its permissions to user 1883.

If you are able to create any file/folder in the persistent storage area (`~/IOTstack/volumes/Mosquitto`), then launch ("up") or restart the Mosquitto container and that does not result in the file changing ownership to 1883:1883 then it implies something else is wrong. Perhaps there is a "user" statement in the compose fragment for Mosquitto? There should not be.

Otherwise, I'd be suspecting some problem with pwfile itself. If you delete (or rename) that file and restart the container, a new null pwfile should be created. Then you can start adding usernames and passwords to it as documented.

**Comment by Paraphraser** [comment]
![31AF50D4-9E41-4220-8E6A-5BF8F758F1BA](https://user-images.githubusercontent.com/34226495/155440044-7a413608-a1c3-4bfa-b99c-27e3f82b4ad4.jpeg)

config and pwfile folders and contents come from the template. The others are created by Mosquitto as it runs. Log may not be there if you let all logging go through docker.

**Comment by the1gofer** [comment]
ok so I've managed to recreate the issue. 

I'm still learning quite bit about linux, containers, etc, so I ended up starting from a fresh image, resetting up IOTstack.  

https://www.dropbox.com/s/8rs4bf2tnmfi9uj/Screen%20Shot%202022-02-25%20at%206.37.16%20PM.png?dl=0

Is it possible it has to do with  the fresh setup? 

https://www.dropbox.com/s/f9m8rdapt10ahp6/Screen%20Shot%202022-02-25%20at%206.41.21%20PM.png?dl=0

**Comment by Paraphraser** [comment]
That's true. Mosquitto is **very** sensitive to **any** of its files being futzed with. That's got nothing to do with IOTstack. In historical terms, Mosquitto was always a problem. It is less of a problem with the self-repair code in place but the self-repair code can't fix everything.

If you really want to open a shell into the Mosquitto container, use "ash":

![7BDC8F70-85B3-42DD-BD8D-BF50213CA850](https://user-images.githubusercontent.com/34226495/155832310-55834253-a1e5-4d42-8168-04a8b8c66abc.jpeg)

It's possible that "restart" isn't strong enough and that a recreate is required:

```
$ cd ~/IOTstack
$ docker-compose up -d --force-recreate mosquitto
```

**Comment by Paraphraser** [comment]
Actually, a restart is sufficient.
![44885460-84FB-47E2-BD45-4FB37C473DA1](https://user-images.githubusercontent.com/34226495/155835236-2f0749cf-aab3-452c-996b-8a90a085e844.jpeg)

**Comment by the1gofer** [comment]
When you say restart you mean `docker restart mosquito`.
